services:
  # 1. Base de Datos SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: kindergarten-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD} 
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  # 2. Backend API
  api:
    build:
      context: ./backend/KindergartenAPI
      dockerfile: Dockerfile
    container_name: kindergarten-api
    ports:
      - "5214:8080" # Mapeamos puerto 5214 de tu PC al 8080 del container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=KindergartenDB;User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - db

  # 3. Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:5214
    container_name: kindergarten-web
    ports:
      - "3000:80" # Mapeamos puerto 3000 de tu PC al 80 de Nginx
    depends_on:
      - api

volumes:
  sqlvolume:

  # --- AGREGA ESTO AL FINAL DEL ARCHIVO ---
networks:
  kindergarten-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1350